version: "3"

services:
  postgres:
    container_name: parcel-db
    image: postgres
    environment:
      POSTGRES_USER: staffs
      POSTGRES_PASSWORD: student
      PGDATA: /data/postgres
    volumes:
      - ./db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped